### ISSUE TITLE
Backspace deletes left and right when between braces

### ISSUE THREAD

**Issue by ivars417** [Sublime-Instincts/BetterTwig#14]
### Summary

When backspacing on characters between braces plugin automatically removes characters on left and right.

### Expected Behaviour

Expected behaviour - as it was before v1.0.4. Backspace removes braces, quotes on left and right when there are no other chars between them.

### Actual Behaviour

After v1.0.4. update backspace removes both left and right characters if they are between braces 

### How to Reproduce

Consider this line: Some random text and {{ some bracy text }} and some extra text

1. Place pointer in any text part inside braces
2. Backspace 
3. Observe how text is being removed on left (expected) and right (unexpected)
4. Note: none of the text is removed on right when backspacing if trying to do it outside braces

### Environment

- Sublime Text build: [3211]
- BetterTwig version: v1.0.4
- Operating System: Windows 10

**Comment by Ultra-Instinct-05** [comment]
Thanks for the report. I had added a backspace key binding to make it easier to come out of empty expression/statement blocks but looks like it's having some deleterious effects. I pushed a new tag release v1.0.5 that removes it.

**Comment by ivars417** [comment]
Great, thanks! Everything works now!
