### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kitsguru** [Sublime-Instincts/BetterTwig#15]
Missing if block, could you add this and its variations? There is no feature request template available.

**Comment by Ultra-Instinct-05** [comment]
Could you elaborate a bit more ? As far as I can see, an `if` block is highlighted just fine. Maybe post some sample code blocks so I can understand.

**Comment by kitsguru** [comment]
Sorry I did not distinguish between snippet and syntax. It is the snippet that is missing, Highlighting works fine.

**Comment by Ultra-Instinct-05** [comment]
Snippets are more of a user thing (meaning snippets are not generic, some users may like them and some don't) than a package providing them (& you can very easily create your own snippets & use them). This package only ships with a few snippets for basic blocks & I am not interested in increasing them. You can find more information on how to create snippets here https://www.sublimetext.com/docs/completions.html#snippets

I am going to close this as a wont fix.
