### ISSUE TITLE
Missing on package control

### ISSUE THREAD

**Issue by thisisjamessmith** [Sublime-Instincts/BetterTwig#22]
This package is marked as "missing" on Package Control, and doesn't appear in the list of installable packages for me.

https://packagecontrol.io/packages/Twig

**Comment by Ultra-Instinct-05** [comment]
Someone reported something similar on discord. Looks like Package Control has some issues with the `v` in `st3-v1.0.7`. Technically speaking, not sure why that matters. I'll cut out a `st3-1.0.8` (without the `v`) release. Let's see what happens.

**Comment by Ultra-Instinct-05** [comment]
Okay. I have gone ahead and released `st3-1.0.8`. Let's see what happens once the crawler picks up the change.

**Comment by Ultra-Instinct-05** [comment]
Okay. So it no longer shows missing on my end. Please confirm.

**Comment by thisisjamessmith** [comment]
Thanks, yes it's there now
