### ISSUE TITLE
Key Binding for comments doesn't seem to be working on MacOS

### ISSUE THREAD

**Issue by mikevaux** [Sublime-Instincts/BetterTwig#24]
### Description of the bug

The key binding for comments on MacOS, (Cmd + /), has stopped creating a twig comment, and started creating an ordinary html comment.

When trying to open the Key Bindings preferences for BetterTwig via Go To Anything (to try and investigate the issue), I get the following popup error:

> The settings file "res://Packages/BetterTwig/resources/keymaps/Default.sublime-keymap" could not be opened

I've tried removing and re-adding the package but it's still not working

### Steps to reproduce

1. Open new file, and set syntax to twig
2. Write `<h1>Hello</h1>`
3. Press Cmd + / to comment out the line / selection

### Expected behavior

`{# <h1>Hello</h1> #}`

### Actual behavior

`<!-- <h1>Hello</h1> -->`

### BetterTwig version

2.0.0

**Comment by Ultra-Instinct-05** [comment]
Thanks for the report. 

> When trying to open the Key Bindings preferences for BetterTwig via Go To Anything (to try and investigate the issue)
> The settings file "res://Packages/BetterTwig/resources/keymaps/Default.sublime-keymap" could not be opened

Can you tell the exact steps that your taking for this ? Cause I don't see why is it flagging a keymap as a settings file.

**Comment by mikevaux** [comment]
That's fine, no worries! I thought the most comprehensive answer to this would be to do a screen recording... Here you go, hope this is helpful!


https://user-images.githubusercontent.com/19553364/150103782-34f78d7e-6210-40d2-ae10-7e33c4ba32b4.mov

(Ignore the bit where I open the help menu - had a momentary blip and forgot the shortcut for a block-level comment!)

**Comment by Ultra-Instinct-05** [comment]
I appreciate the GIF but actually I wanted information on that keybindings error popup you were getting (The steps for that). That's what my previous comment was about (If you see the portion of your reply I quoted). Because I can't reproduce that.

Regarding the Twig comment not working, I have a fix for that already and it will be available in `2.0.1`

**Comment by mikevaux** [comment]
Ah, that's great about the comment fix - thanks!

Apologies, I'm not sure I follow exactly what you're wanting - the screen recording shows the exact steps to getting the keybindings error - the error shows right at the end after installing the package and attempting to open "Preferences: BetterTwig Key Bindings" via the Command Palette.

_However_, I'm wondering if the file is not being installed to the correct location - there is no 'BetterTwig' folder in my Packages folder... Should it be in `Packages/User`? I'm not very familiar with this, but let me know if you want me to look at what files I do / don't have!

**Comment by Ultra-Instinct-05** [comment]
Totally my bad. Sorry ! I did not watch the GIF till the end. I understand why opening the key bindings file errors out like that. I will get that addressed in `2.0.1` as well.

**Comment by Ultra-Instinct-05** [comment]
I have just published `v2.0.1`. Once the PC crawler picks up the changes, the updated should be available. Let me know if it fixes the issues on your end,

**Comment by mikevaux** [comment]
Both things now seem to be working! Thank you!
