### ISSUE TITLE
Work better with Tailwind classes and custom values

### ISSUE THREAD

**Issue by mgussekloo** [Sublime-Instincts/BetterTwig#33]
### Description of your enhancement/feature request proposal.

Hi, example of some Tailwind markup for which this plugin could be enhanced:

`<div class="text-[#000AAA]">Lorem</div>`

When typing `text-[#`, the Twig package autocompletes with curly brackets so it becomes `text-[#{}`, but this is obviously the wrong behavior. If the Package could understand this it would be great.

### Alternatives.

Currently I'm manually fixing this erroneous autocompletes.

**Comment by deathaxe** [comment]
This would literly mean to gate or remove the `#` binding.

https://github.com/Sublime-Instincts/BetterTwig/blob/506db5fc3a6008679a15297927c04102388fd6fb/resources/keymaps/Default.sublime-keymap#L38-L52

Maybe somewhat too generic anyway, as `#` is rather common to be used in color codes and other sorts of text.
