### ISSUE TITLE
[BUG] `same as` is not scoped

### ISSUE THREAD

**Issue by jfcherng** [Sublime-Instincts/BetterTwig#5]
### Summary

From the docs, `same as` is the same with `===` in PHP. (Note that there is no `===` in Twig)
https://twig.symfony.com/doc/3.x/tests/sameas.html
Maybe `===` worth a `invalid` scope since it's really a common mistake in Twig for PHP dev.

### Problematic Twig template.

```jinja
{% if foo.attribute is same as(false) %}
    the foo attribute really is the 'false' PHP value
{% endif %}
```

**Comment by Ultra-Instinct-05** [comment]
This is fixed as of v1.0.4
