### ISSUE TITLE
Add to Package Control

### ISSUE THREAD

**Issue by andremacola** [Sublime-Instincts/BetterTwig#8]
Tried to find BetterTwig on Package Control but did not found.

**Comment by Ultra-Instinct-05** [comment]
A PR has been submitted to the PC channel (https://github.com/wbond/package_control_channel/pull/8014) to have this package on PC but before that, it has to be reviewed and approved before it can be merged.

**Comment by Ultra-Instinct-05** [comment]
Closing as this has now been added to PC.
